version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      # - echo Executing Pre Build Phase
      # - echo Logging in to Amazon ECR...
      # - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      # - echo Executing Pre Build
      # - echo building docker image...
      # - docker build -t eksflask .
      # - docker tag eksflask:latest 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com/eksflask:latest
      # - docker push 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com/eksflask:latest
      - CREDENTIALS=$(aws sts assume-role --role-arn $EKS_KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      # - kubectl apply -f deployment.yaml
  post_build:
    commands:
      - echo Executing Post Build Phase
      - echo Build completed on `date`

    