version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Executing Pre Build Phase
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com
      # - apt-get install -y python3-venv
      # - python3.6 -m venv test_venv
      # - . test_venv/bin/activate
      # - pip install --upgrade pip
      # - pip install .
      # - pip install -r tests/requirements.txt
      # - rm -rf dspt
      # - mkdir test-reports
  build:
    commands:
      - echo Executing Pre Build
      - echo building docker image...
      - docker build -t eksflask .
      - docker tag eksflask:latest 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com/eksflask:latest
      - docker push 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com/eksflask:latest
      # - kubectl apply -f deployment.yaml
  post_build:
    commands:
      - echo Executing Post Build Phase
      - echo Build completed on `date`

    