apiVersion: apps/v1
kind: Deployment
metadata:
  name: final02
spec:
  selector:
    matchLabels:
      app: final02
  replicas: 2
  template:
    metadata:
      labels:
        app: final02
    spec:
      containers:
      - name: final02
        image: 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com/final02:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000