apiVersion: apps/v1
kind: Deployment
metadata:
  name: hzflaskwebsite
spec:
  selector:
    matchLabels:
      app: hzflaskwebsite
  replicas: 2
  template:
    metadata:
      labels:
        app: hzflaskwebsite
    spec:
      containers:
      - name: hzflaskwebsite
        image: 687639674385.dkr.ecr.ap-southeast-1.amazonaws.com/eksflask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000